#!/usr/bin/env python3
"""Static contract checks for the experimental real A2M12 integration."""

from pathlib import Path


ROOT = Path(__file__).resolve().parents[3]
LAUNCH = ROOT / "real_robot/cuvslam/deployment/isaac_ros/isaac_ros_visual_slam_d435i_rplidar.launch.py"
REAL_LAUNCH = ROOT / "real_robot/cuvslam/deployment/isaac_ros/isaac_ros_visual_slam_d435i_real.launch.py"
LIDAR_CONFIG = ROOT / "real_robot/cuvslam/config/rplidar/a2m12.yaml"
SLAM_CONFIG = ROOT / "real_robot/cuvslam/config/real_d435i_rplidar_slam_toolbox.yaml"
LIDAR_ODOM_CONFIG = ROOT / "real_robot/cuvslam/config/real_d435i_rplidar_lidar_odom.yaml"
EKF_SHADOW_CONFIG = ROOT / "real_robot/cuvslam/config/real_d435i_rplidar_ekf_shadow.yaml"
RUNNER = ROOT / "real_robot/cuvslam/tools/run_real_d435i_rplidar.sh"
R2_RUNNER = ROOT / "real_robot/cuvslam/tools/run_real_d435i_r2.sh"
LOCALIZATION_RUNNER = ROOT / "real_robot/cuvslam/tools/run_experimental_localization.sh"
COLLECTOR = ROOT / "real_robot/cuvslam/tools/collect_real_d435i_odom_live.py"
IMAGE_QUALITY = ROOT / "real_robot/cuvslam/tools/collect_real_d435i_image_quality.py"
GUI = ROOT / "real_robot/cuvslam/tools/real_d435i_axis_web_gui.py"
PREFLIGHT = ROOT / "real_robot/cuvslam/tools/check_real_d435i_lidar_ekf_dependencies.sh"
ODOM_GUARD = ROOT / "real_robot/cuvslam/tools/odom_contract_guard.py"
SCAN_TF_GATE = ROOT / "real_robot/cuvslam/tools/scan_tf_gate.py"


def require(text, needle, label):
    if needle not in text:
        raise AssertionError(f"{label}: missing {needle!r}")


def main():
    launch = LAUNCH.read_text()
    real_launch = REAL_LAUNCH.read_text()
    lidar_config = LIDAR_CONFIG.read_text()
    slam_config = SLAM_CONFIG.read_text()
    lidar_odom_config = LIDAR_ODOM_CONFIG.read_text()
    ekf_shadow_config = EKF_SHADOW_CONFIG.read_text()
    runner = RUNNER.read_text()
    r2_runner = R2_RUNNER.read_text()
    localization_runner = LOCALIZATION_RUNNER.read_text()
    collector = COLLECTOR.read_text()
    image_quality = IMAGE_QUALITY.read_text()
    gui = GUI.read_text()
    preflight = PREFLIGHT.read_text()
    odom_guard = ODOM_GUARD.read_text()
    scan_tf_gate = SCAN_TF_GATE.read_text()

    require(launch, 'package="sllidar_ros2"', "integrated launch")
    require(launch, 'executable="sllidar_node"', "integrated launch")
    require(launch, 'executable="async_slam_toolbox_node"', "integrated launch")
    require(launch, '"base_frame": "base_link"', "integrated launch")
    require(launch, '"publish_map_to_odom_tf": "false"', "integrated launch")
    require(launch, '"enable_mapping": "false"', "integrated launch")
    require(launch, 'LaunchConfiguration("enable_imu_fusion")', "integrated launch runtime override")
    require(launch, 'LaunchConfiguration("infra_profile")', "integrated launch runtime override")
    require(launch, 'LaunchConfiguration("enable_observations_view")', "integrated launch diagnostics override")
    require(launch, 'LaunchConfiguration("enable_lidar_odom")', "integrated launch LiDAR odom switch")
    require(launch, 'LaunchConfiguration("enable_ekf_shadow")', "integrated launch EKF switch")
    require(launch, 'package="rf2o_laser_odometry"', "integrated launch LiDAR odom")
    require(launch, 'package="robot_localization"', "integrated launch EKF")
    require(launch, '"/odometry/filtered_shadow"', "integrated launch shadow output")
    require(launch, '"odom_contract_guard.py"', "odom contract guard script")
    require(launch, '"/fusion/visual_odom"', "guarded visual odom topic")
    require(launch, '"/fusion/lidar_odom"', "guarded LiDAR odom topic")
    require(launch, '"0,1,5"', "visual selected twist fields")
    require(launch, '"0,5"', "LiDAR selected twist fields")
    require(launch, '"enable_observations_view",\n                "false"', "integrated launch diagnostics declaration")
    require(launch, '"initial_reset": initial_reset', "integrated launch")
    require(launch, '"initial_reset",\n                "false"', "integrated launch reset default")
    require(launch, '"base_link",\n            "rplidar_link"', "static LiDAR TF")
    require(launch, 'frame_id", "rplidar_link"', "A2M12 frame default")
    require(launch, 'remappings=[("/scan", "/scan_raw")]', "raw scan input")
    require(launch, 'scan_tf_gate_script', "scan TF gate launch")
    require(launch, '"enable_scan_tf_gate",\n                "true"', "scan TF gate default")

    require(real_launch, 'LaunchConfiguration("base_frame")', "real launch base override")
    require(real_launch, 'LaunchConfiguration("publish_map_to_odom_tf")', "real launch map TF override")
    require(real_launch, 'LaunchConfiguration("publish_odom_to_base_tf")', "real launch odom TF override")

    require(lidar_config, "serial_baudrate: 256000", "A2M12 baud")
    require(lidar_config, "frame_id: rplidar_link", "A2M12 frame")
    require(slam_config, "base_frame: base_link", "slam_toolbox base frame")
    require(slam_config, "scan_topic: /scan", "slam_toolbox scan topic")
    require(lidar_odom_config, "odom_topic: /lidar/odom", "LiDAR odom topic")
    require(lidar_odom_config, "publish_tf: false", "LiDAR odom TF isolation")
    require(launch, '("/tf", "/shadow/lidar_odom_tf_unused")', "LiDAR odom defensive TF remap")
    require(ekf_shadow_config, "odom0: /fusion/visual_odom", "EKF guarded visual input")
    require(ekf_shadow_config, "odom1: /fusion/lidar_odom", "EKF guarded LiDAR input")
    require(ekf_shadow_config, "odom0_differential: false", "EKF visual no duplicate differential pose")
    require(ekf_shadow_config, "odom1_differential: false", "EKF LiDAR no duplicate differential pose")
    require(ekf_shadow_config, "true, false, false, false, false, true", "EKF LiDAR no fixed vy")
    if "odom0: /visual_slam/tracking/odometry" in ekf_shadow_config:
        raise AssertionError("EKF must consume guarded visual odometry")
    if "odom1: /lidar/odom" in ekf_shadow_config:
        raise AssertionError("EKF must consume guarded LiDAR odometry")
    require(ekf_shadow_config, "publish_tf: false", "EKF TF isolation")
    require(launch, '("/tf", "/shadow/ekf_tf_unused")', "EKF defensive TF remap")
    require(runner, 'CONTAINER="real_d435i_rplidar"', "integration runner")
    require(runner, "real_d435i_r2", "R2 exclusion")
    require(runner, "real_d435i_r1p5_axis_gui", "R1.5 exclusion")
    require(runner, "ros2 service call /stop_motor std_srvs/srv/Empty", "A2M12 motor stop service")
    require(runner, "stopped_components=d435i,cuvslam,a2m12_lidar,slam_toolbox", "mapping cleanup ownership")
    require(runner, "telemetry)", "mapping telemetry entry point")
    require(runner, "preflight)", "mapping dependency preflight entry point")
    require(runner, "estimator_stack", "mapping estimator selection")
    require(runner, "ekf_shadow", "mapping EKF shadow selection")
    require(runner, "CUVSLAM_LIDAR_YAW", "fixed-mount yaw environment fallback")
    require(runner, "CUVSLAM_LIDAR_X", "fixed-mount x environment fallback")
    require(runner, "CUVSLAM_LIDAR_Y", "fixed-mount y environment fallback")
    require(runner, "CUVSLAM_LIDAR_Z", "fixed-mount z environment fallback")
    require(runner, "validate_lidar_value lidar_yaw", "fixed-mount yaw validation")
    require(runner, "validate_lidar_value lidar_x", "fixed-mount x numeric validation")
    require(runner, "validate_lidar_value lidar_y", "fixed-mount y numeric validation")
    require(runner, "validate_lidar_value lidar_z", "fixed-mount z numeric validation")
    require(runner, "lidar_x:=${lidar_x}", "fixed-mount x launch forwarding")
    require(runner, "lidar_y:=${lidar_y}", "fixed-mount y launch forwarding")
    require(runner, "lidar_z:=${lidar_z}", "fixed-mount z launch forwarding")
    require(runner, "lidar_yaw:=${lidar_yaw}", "fixed-mount yaw launch forwarding")
    require(runner, "enable_scan_tf_gate:=${scan_tf_gate}", "scan TF gate launch forwarding")
    require(runner, "/lidar/odom", "mapping LiDAR odom recording")
    require(runner, "/scan_raw", "raw scan recording")
    require(runner, "/fusion/visual_odom", "guarded visual odom recording")
    require(runner, "/fusion/lidar_odom", "guarded LiDAR odom recording")
    require(runner, "/fusion/odom_contract_diagnostics", "odom guard diagnostics recording")
    require(runner, "/diagnostics", "EKF diagnostics recording")
    require(preflight, "rf2o_laser_odometry", "LiDAR odom dependency preflight")
    require(preflight, "robot_localization", "EKF dependency preflight")
    require(odom_guard, "def validate_message", "odom contract validator")
    require(odom_guard, "twist covariance", "odom covariance validation")
    require(odom_guard, "timestamp is not increasing", "odom timestamp validation")
    require(odom_guard, "odom_contract_guard/", "odom guard diagnostics")
    require(runner, "quality)", "mapping quality entry point")
    require(runner, "record_start)", "mapping recording start entry point")
    require(runner, "record_stop)", "mapping recording stop entry point")
    require(runner, "/map", "mapping bag map topic")
    require(runner, 'output="/workspaces/isaac_ros_data/experiments/real_d435i_rplidar/${run_name}/rosbag"', "mapping container bag path")
    require(runner, 'container_output_dir="/workspaces/isaac_ros_data/experiments/real_d435i_rplidar/${run_name}"', "mapping container log path")
    require(runner, "low_light_motion", "mapping low-light motion profile")
    require(runner, "enable_observations_view:=${observations_view}", "mapping diagnostics forwarding")
    require(runner, "emitter_override", "mapping emitter A/B override")
    require(runner, "/camera/infra1/metadata", "mapping camera metadata recording")
    require(runner, "/visual_slam/vis/pose_graph_edges", "mapping pose graph recording")
    require(r2_runner, "low_light_motion", "R2 low-light motion profile")
    require(r2_runner, "emitter_override", "R2 emitter A/B override")
    require(r2_runner, "/camera/infra1/metadata", "R2 camera metadata recording")
    require(collector, "OccupancyGrid", "live map collector message")
    require(collector, 'create_subscription(OccupancyGrid, "/map"', "live map topic")
    require(collector, 'create_subscription(LaserScan, "/scan"', "live scan topic")
    require(collector, 'create_subscription(Odometry, "/lidar/odom"', "live LiDAR odom topic")
    require(collector, 'create_subscription(Odometry, "/odometry/filtered_shadow"', "live EKF shadow topic")
    require(collector, '"estimator_comparisons"', "live odometry comparison telemetry")
    require(collector, '"estimator_contribution"', "live EKF contribution telemetry")
    require(collector, '"odom_guard_diagnostics"', "live odom guard diagnostics telemetry")
    require(collector, '"/fusion/odom_contract_diagnostics"', "live odom guard diagnostics topic")
    require(collector, "def covariance_summary", "live odometry covariance telemetry")
    require(collector, '"fused_field_warning"', "live odometry covariance gate")
    require(collector, 'DiagnosticArray', "live EKF diagnostics message")
    require(collector, "def diagnostic_level_value", "diagnostic uint8 compatibility")
    require(collector, 'diagnostic_level_value(getattr(diagnostic, "level", None))', "diagnostic uint8 compatibility")
    require(collector, "TransformListener", "live TF projection")
    require(collector, 'print("LIVE_MAP "', "live map telemetry")
    require(collector, 'print(\n            "LIVE_SCAN "', "live scan telemetry")
    require(collector, "scan_map_alignment", "timestamped scan-map alignment telemetry")
    require(collector, "alignment_map_revision", "dynamic map distance-field refresh")
    require(collector, "map_pose_for_sample", "timestamped map-frame path projection")
    require(collector, "scan_timing_payload", "LaserScan timing and TF telemetry")
    require(collector, '"time_increment_us"', "LaserScan time increment telemetry")
    require(collector, '"timestamp_age_ms"', "LaserScan timestamp age telemetry")
    require(collector, '"scan_end_age_ms"', "LaserScan end timestamp age telemetry")
    require(collector, '"tf_lookup_delta_ms"', "scan-to-TF timestamp delta telemetry")
    require(collector, "pending_scans", "bounded timestamped scan display queue")
    require(collector, "resolve_pending_scans", "delayed exact-TF scan display")
    require(collector, '"timestamped_delayed"', "delayed exact-TF scan display mode")
    require(collector, '"display_delay_ms"', "delayed scan display telemetry")
    require(collector, '"queue_drops"', "bounded scan display queue telemetry")
    require(collector, "resolve_pending_map_poses", "delayed exact-TF map path display")
    require(collector, '"map_path_projection"', "map path projection telemetry")
    require(collector, '"timestamp_age_ms"', "source timestamp age telemetry")
    require(collector, "PoseWithCovarianceStamped", "AMCL localization telemetry")
    require(collector, '"localization_pose"', "AMCL localization telemetry payload")
    require(scan_tf_gate, "class ScanTfGate", "scan TF gate node")
    require(scan_tf_gate, "can_transform", "scan TF gate timestamp check")
    require(scan_tf_gate, '"/scan_raw"', "scan TF gate raw topic")
    require(scan_tf_gate, '"/scan"', "scan TF gate output topic")
    require(launch, '"--check-hz", "30.0"', "scan TF gate launch arguments")
    if '"--ros-args", "-p", "use_sim_time:=false"' in launch:
        raise AssertionError("scan TF gate must not receive ROS-only CLI arguments")
    require(image_quality, "from realsense2_camera_msgs.msg import Metadata", "image metadata collector")
    require(image_quality, '"/camera/infra1/metadata"', "left image metadata topic")
    require(image_quality, '"/camera/infra2/metadata"', "right image metadata topic")
    require(image_quality, '"metadata": {', "metadata quality output")
    require(gui, 'id="mapping-canvas"', "GUI mapping canvas")
    require(gui, 'id="localization-canvas"', "GUI localization canvas")
    require(gui, 'id="localization-start"', "GUI localization start button")
    require(gui, '"/api/localization/start"', "GUI localization start API")
    require(gui, '"/api/localization/stop"', "GUI localization stop API")
    require(gui, "localization_pose", "GUI AMCL pose display")
    require(gui, "localizationOverlap", "GUI scan-map overlap coloring")
    require(gui, "REMOTE_LOCALIZATION_SCRIPT_CANDIDATES", "GUI localization runner path")
    require(gui, 'id="r2-estimator"', "GUI estimator selection")
    require(gui, "estimator_stack", "GUI estimator runtime record")
    require(gui, "estimator_comparisons", "GUI estimator comparison state")
    require(gui, "estimator_contribution", "GUI estimator contribution state")
    require(gui, "estimator_paths", "GUI multi-estimator paths")
    require(gui, "estimator_covariance", "GUI covariance warning state")
    require(gui, "timestamp skew", "GUI estimator time skew log")
    require(gui, "ekf_internal", "GUI EKF internal diagnostics state")
    require(gui, '"odom_guard_diagnostics"', "GUI odom guard diagnostics state")
    require(gui, "Odometry input guard", "GUI odom guard work log")
    require(gui, "EKF 介入程度（軌跡推估", "GUI EKF contribution log")
    require(gui, "LIVE_MAP", "GUI map telemetry parser")
    require(gui, "LIVE_SCAN", "GUI scan telemetry parser")
    require(gui, 'append_run_trace("scan_telemetry"', "GUI scan timing trace")
    require(gui, "LiDAR 時間診斷", "GUI scan timing summary")
    require(gui, "scan_stamp=", "GUI scan timing work log")
    require(gui, "mapping_path", "GUI map-frame path")
    require(gui, "REMOTE_RPLIDAR_SCRIPT_CANDIDATES", "GUI mapping runner path")
    require(gui, "active_runtime_command", "GUI active runtime routing")
    require(gui, '"start", mode, profile, lighting, diagnostics', "GUI mapping parameter forwarding")
    require(gui, "CUVSLAM_LIDAR_YAW", "GUI fixed-mount yaw setting")
    require(gui, "CUVSLAM_LIDAR_X", "GUI fixed-mount x setting")
    require(gui, "CUVSLAM_LIDAR_Y", "GUI fixed-mount y setting")
    require(gui, "CUVSLAM_LIDAR_Z", "GUI fixed-mount z setting")
    require(gui, "LiDAR fixed mount TF", "GUI fixed-mount work-record logging")
    require(gui, '"lidar_mount_requested"', "GUI fixed-mount runtime record")
    require(gui, "low_light_motion", "GUI low-light motion profile")
    require(gui, 'id="r2-emitter"', "GUI emitter A/B selector")
    require(gui, '"emitter"', "GUI emitter A/B parameter forwarding")
    require(gui, "IR Projector A/B Override:", "GUI emitter A/B work log")
    require(gui, 'onclick="copyProcessLog()"', "GUI process log copy button")
    require(gui, "async function copyProcessLog()", "GUI process log copy function")
    require(gui, 'onclick="clearProcessLog()"', "GUI process log clear button")
    require(gui, '"/api/logs/clear"', "GUI process log clear endpoint")
    require(gui, 'id="quality-exposure"', "GUI actual exposure display")
    require(gui, 'id="quality-gain"', "GUI actual gain display")
    require(gui, '"input_flags": input_flags', "GUI image quality gate")
    require(gui, '"geometry_gate": geometry_gate', "GUI geometry quality gate")
    require(gui, "observed_quality_flags", "GUI observed image flags retention")
    require(gui, "worst_geometry_gate", "GUI worst geometry retention")
    require(gui, "整段轉向幾何最差觀測", "GUI worst geometry summary")
    require(gui, "Worst Geometry:", "GUI final worst geometry log")
    require(gui, '"metadata": data.get("metadata", {})', "GUI motion metadata timeline")
    require(gui, "=== Runtime 實驗設定（Requested） ===", "GUI requested runtime log")
    require(gui, "Requested Exposure:", "GUI requested camera log")
    require(gui, "Actual Exposure L/R:", "GUI actual camera log")
    require(gui, "Actual Gain L/R:", "GUI actual gain log")
    require(gui, "Observations View / Recording:", "GUI diagnostics log")
    require(gui, "=== Quality / Geometry Final ===", "GUI final quality log")
    require(gui, '"requested_runtime": requested_runtime_settings', "GUI session runtime record")
    require(localization_runner, "experimental_candidate_localization", "localization runner container")
    require(localization_runner, "candidate_amcl", "localization runner TF owner")
    require(localization_runner, "conflicting runtime is active", "localization runner owner guard")

    print("REAL_D435I_RPLIDAR_CONTRACT_PASS")


if __name__ == "__main__":
    main()
